version: '2'
services:
  lb:
    restart: always
    image: 'dockercloud/haproxy:latest'
    networks:
      - front
    links:
      - web
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt/live/claroline.loc/fullchain.pem:/certs/fullchain.pem
    environment:
      CERT_FOLDER: /certs/
      FORCE_SSL: true

  web:
    restart: always
    build: web/
    networks:
      - front
      - back
    volumes:
      - data:/var/www/html/claroline
    volumes_from:
      - lb
    environment:
      VIRTUAL_HOST: https://claroline.loc

  db:
    restart: always
    image: mysql
    networks:
      - back
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: claroline
      MYSQL_PASSWORD: claroline
      MYSQL_DATABASE: claroline

  chat:
    restart: always
    image: prosody/prosody
    ports:
      - '81:80'
      - '5222:5222'

  tools:
    build: tools/
    volumes:
      - data:/var/www/html/claroline

networks:
  front:
  back:

volumes:
  data:
  mysql:
