version: '2'
services:
  le:
    image: nickbreen/letsencrypt-combined:v1.1.0
    volumes:
      - /etc/letsencrypt
      - /var/lib/letsencrypt
    volumes_from:
      - lb
      - web
    environment:
      CRON_D_LE: |
        @monthly root le renew 2>&1 | logger --tag le-renew

  lb:
    restart: always
    image: 'dockercloud/haproxy:latest'
    networks:
      - front
    links:
      - web
    ports:
      - '80:80'
      - '443:443'
      - '1936:1936'
    volumes:
      #- /certs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      #CERT_FOLDER: /certs/
      STATS_AUTH: "auth:auth"
      STATS_PORT: 1936
      #FORCE_SSL: "yes"
      #SSL_CERT: "YOUR_CERT_TEXT"

  web:
    restart: always
    build: web/
    networks:
      - front
      - back
    #  - elk
    volumes:
      - data:/var/www/html/claroline
    environment:
      VIRTUAL_HOST: http://claroline.loc
      #VIRTUAL_HOST: http://claroline.loc, https://claroline.loc

  db:
    restart: always
    image: mysql
    networks:
      - back
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: claroline
      MYSQL_PASSWORD: claroline
      MYSQL_DATABASE: claroline

  chat:
    restart: always
    image: prosody/prosody
    ports:
      - '81:80'
      - '5222:5222'

  #elasticsearch:
  #   restart: always
  #   image: elasticsearch:5.0
  #   networks:
  #     - elk
  #   ports:
  #     - '9200:9200'
  #     - '9300:9300'
  #
  # logstash:
  #   restart: always
  #   image: logstash:5.0
  #   ports:
  #     - '12201:12201'
  #   networks:
  #     - elk
  #   links:
  #     - elasticsearch
  #   environment:
  #     - 'input { gelf { codec => "json" } } output { elasticsearch { hosts => "elasticsearch:9200" } }'
  #
  # kibana:
  #   restart: always
  #   image: kibana:5.0
  #   networks:
  #     - elk
  #   links:
  #     - elasticsearch
  #   ports:
  #     - '5601:5601'

  tools:
    build: tools/
    volumes:
      - data:/var/www/html/claroline

networks:
  front:
  back:
  #elk:

volumes:
  data:
  mysql:
